version: "3.5"
services:
  operator:
    image: "operator.stakewise-operator-prater.dnp.dappnode.eth:0.1.0"
    build:
      context: operator
      args:
        UPSTREAM_VERSION: v1.0.5.beta
    restart: unless-stopped
    volumes:
      - "stakewise:/app/data"
    environment:
      - VAULT_CONTRACT_ADDRESS
      - OPERATOR_WALLET_PASSWORD
      - KEYSTORES_PASSWORD
volumes:
  stakewise: {}
