version: "3.5"
services:
  operator:
    build:
      context: operator
      args:
        UPSTREAM_VERSION: v1.1.0
    restart: unless-stopped
    volumes:
      - "stakewise:/app/data"
    environment:
      - VAULT_CONTRACT_ADDRESS
      - VALIDATORS_NUMBER
      - LOG_LEVEL=INFO
volumes:
  stakewise: {}
