version: "3.5"
services:
  operator:
    build:
      context: operator
      args:
        UPSTREAM_VERSION: v1.2.0
    restart: unless-stopped
    volumes:
      - stakewise:/app/data/stakewise
      - mnemonic:/app/data/mnemonic
    environment:
      - VAULT_CONTRACT_ADDRESS
      - VALIDATORS_NUMBER
      - LOG_LEVEL=INFO
    image: operator.stakewise-operator-holesky.dnp.dappnode.eth:0.1.0
volumes:
  stakewise: {}
  mnemonic: {}
