version: "3.5"
services:
  operator:
    build:
      context: operator
      args:
        UPSTREAM_VERSION: v1.1.0.dev1
    restart: unless-stopped
    volumes:
      - "stakewise:/app/data"
    environment:
      - VAULT_CONTRACT_ADDRESS
      - OPERATOR_WALLET_PASSWORD
      - KEYSTORES_PASSWORD
volumes:
  stakewise: {}
