version: "3.5"
services:
  operator:
    image: "operator.stakewise-operator-prater.dnp.dappnode.eth:0.1.0"
    build:
      context: ./operator
    restart: unless-stopped
    volumes:
      - "stakewise:/data"
    environment:
      - VAULT_CONTRACT_ADDRESS
      - OPERATOR_WALLET_PASSWORD
      - KEYSTORES_PASSWORD
      - HARVEST_VAULT=false
volumes:
  stakewise: {}
